name: ElectronBuilder
on: [workflow_dispatch]
env:
  GH_TOKEN: ${{ github.token }}
permissions: write-all
jobs:
  build_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 22
    - name: install dependencies
      run: npm install
    - name: publish
      run: npm run build:linux

  build_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 22
    - name: install dependencies
      run: npm install
    - name: publish
      run: npm run build:mac

  build_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 22
    - name: install dependencies
      run: npm install
    - name: publish
      run: npm run build:win